Add Other benchmarks from Hotel app
ease-lab/vSwarm pull request #152
Opened 2022-05-08 07:53 UTC by dhschall

This PR adds the remaining functions from the Hotel application to vSwarm.
They are not exactly as geo.
Once Geo is merged this can be easily integrated

2022-05-09 19:07 UTC, dhschall commented
Knative checks are still failing. I suppose its the same problem with the runners again.
Maybe tomorrow morning it will work again...

2022-05-10 13:45 UTC, ustiugov requested changes
LGTM although I didn't make a very thorough pass, just skimmed.

Minor change:

- [ ] please double check to build and use vhiveease/ images for mongodb and memcached, etc

2022-05-10 13:45 UTC, ustiugov commented on benchmarks/hotel-app/yamls/docker-compose/dc-rate-tracing.yaml
> +    image: mongo:4.2
please double check to use check vhiveease/ images for mongodb and memcached, etc

2022-05-10 22:35 UTC, ustiugov approved these changes

2022-05-11 18:33 UTC, merged