Fix Authentification benchmark
ease-lab/vSwarm pull request #162
Opened 2022-05-10 20:47 UTC by dhschall

- Vulnerability issue #160
- Wrong input arguments #161
- Tracing for AES and Auth in docker

2022-05-10 22:32 UTC, ustiugov requested changes
lgtm, just a minor fix

2022-05-10 22:32 UTC, ustiugov commented on benchmarks/auth/yamls/docker-compose/dc-auth-nodejs-tracing.yaml
> +    # environment:
uncomment?

2022-05-11 12:41 UTC, dhschall commented on benchmarks/auth/yamls/docker-compose/dc-auth-nodejs-tracing.yaml
> +    # environment:
Thanks for noting that

2022-05-11 22:13 UTC, ustiugov approved these changes

2022-05-11 22:50 UTC, merged