Download JSON traces from Zipkin
ease-lab/vSwarm pull request #241
Opened 2022-08-11 14:40 UTC by cvetkovic

2022-08-11 15:15 UTC, sk1tter approved these changes
LGTM

2022-08-11 15:15 UTC, sk1tter commented on tools/trace-plotter/main.go
> +	fmt.Println("Downloading traces")
Maybe use logging?

2022-08-11 15:34 UTC, ustiugov requested changes
some coding style corrections needed

2022-08-11 15:34 UTC, ustiugov commented on tools/trace-plotter/main.go
> +	}
Coding style suggestion

```suggestion
        if *download != "" {
		downloadTraces(parsedE2ETraces)
	}
	if *skipPlotting {
	    return
	}
	page := components.NewPage()
	page.PageTitle = "Trace Plots"

	parsedSystemTraces, systemDurations := ParseTraces(traces, "system")

	page.AddCharts(
		PlotGraph(parsedE2ETraces, e2eDurations, *zipkinURL, "e2e"),
		PlotGraph(parsedSystemTraces, systemDurations, *zipkinURL, "system"),
	)

	if filepath.Ext(*fileName) != ".html" {
		*fileName += ".html"
	}
	f, _ := os.Create(*fileName)
	if err := page.Render(io.MultiWriter(f)); err != nil {
		log.Errorf("Error rendering plot: %s", err)
	}
```

2022-08-11 15:34 UTC, ustiugov commented on tools/trace-plotter/main.go
> +	fmt.Println("Downloading traces")
yes for sure

2022-08-12 07:49 UTC, cvetkovic commented
Fixed all the comments.

2022-08-12 12:01 UTC, ustiugov approved these changes

2022-08-12 12:03 UTC, merged