Bump up online-shop to version v0.3.9
ease-lab/vSwarm pull request #251
Opened 2022-08-26 11:39 UTC by dhschall

Closes #227 
Fixes #245

2022-08-26 23:17 UTC, dhschall commented
Fix online-shop functions

2022-08-30 13:59 UTC, ustiugov requested changes
LGTM but please fix the typos.

2022-08-30 13:59 UTC, ustiugov commented on .github/workflows/e2e-online-shop.yml
> +          ./test-client --addr $url:$NODEPORT --name "Example text for AES CI"
```suggestion
          ./test-client --addr $url:$NODEPORT --name "Example text for CI"
```

2022-08-30 13:59 UTC, ustiugov commented on benchmarks/online-shop/README.md
>  > Warning: This is just a script for your convince. No guarantee that every will work afterwards.
```suggestion
> Warning: This is just a script for your convenience. No guarantee that everything will work afterwards.
```

2022-08-31 14:47 UTC, dhschall commented
Spelling is fixed and also your suggestion is applied.
Can we merge?

2022-08-31 15:30 UTC, merged